FROM parity/parity:v1.10.2

RUN apt-get update && apt-get install curl -y && apt-get install jq -y

RUN mkdir -p /mnt/io.parity.ethereum

VOLUME ["/mnt/io.parity.ethereum"]

RUN mkdir -p /etc/poa-chain

COPY ./configs /etc/poa-chain/

COPY ./scripts /scripts/

# Security issue here - as secret shared by all instances, TODO: change that in future
COPY ./secrets /secrets

EXPOSE 8080
EXPOSE 8180
EXPOSE 8545
EXPOSE 8546
EXPOSE 30303

# For the signer
RUN mkdir -p ~/.local/share/io.parity.ethereum/signer

